require_relative './../lib/digits_to_word_converter.rb'
require 'test/unit'

class TestDigitsToWordConverter < Test::Unit::TestCase

  def test_parser
    assert_equal(DigitsToWordConverter.new.parse('6686787825'), [%w(noun struck), %w(onto struck), %w(motor truck), %w(motor usual), %w(nouns truck), %w(nouns usual), ['motortruck'], %w(mot opt puck), %w(mot opt ruck), %w(mot opt suck), %w(mot ort puck), %w(mot ort ruck), %w(mot ort suck), %w(not opt puck), %w(not opt ruck), %w(not opt suck), %w(not ort puck), %w(not ort ruck), %w(not ort suck), %w(oot opt puck), %w(oot opt ruck), %w(oot opt suck), %w(oot ort puck), %w(oot ort ruck), %w(oot ort suck), %w(mot opts taj), %w(mot opus taj), %w(mot orts taj), %w(not opts taj), %w(not opus taj), %w(not orts taj), %w(oot opts taj), %w(oot opus taj), %w(oot orts taj), %w(noun pup taj), %w(noun pur taj), %w(noun pus taj), %w(noun sup taj), %w(noun suq taj), %w(onto pup taj), %w(onto pur taj), %w(onto pus taj), %w(onto sup taj), %w(onto suq taj)])
    assert_equal(DigitsToWordConverter.new.parse('2282668687'), [%w(act amounts), %w(act contour), %w(bat amounts), %w(bat contour), %w(cat amounts), %w(cat contour), %w(acta mounts), ['catamounts'], %w(act boo tots), %w(act boo tour), %w(act con tots), %w(act con tour), %w(act coo tots), %w(act coo tour), %w(bat boo tots), %w(bat boo tour), %w(bat con tots), %w(bat con tour), %w(bat coo tots), %w(bat coo tour), %w(cat boo tots), %w(cat boo tour), %w(cat con tots), %w(cat con tour), %w(cat coo tots), %w(cat coo tour), %w(act boot mus), %w(act boot nus), %w(act boot our), %w(act coot mus), %w(act coot nus), %w(act coot our), %w(bat boot mus), %w(bat boot nus), %w(bat boot our), %w(bat coot mus), %w(bat coot nus), %w(bat coot our), %w(cat boot mus), %w(cat boot nus), %w(cat boot our), %w(cat coot mus), %w(cat coot nus), %w(cat coot our), %w(acta mot mus), %w(acta mot nus), %w(acta mot our), %w(acta not mus), %w(acta not nus), %w(acta not our), %w(acta oot mus), %w(acta oot nus), %w(acta oot our)])
    assert_equal(DigitsToWordConverter.new.parse('2222738275'), [%w(cabaret ark), %w(cabaret ask), %w(aba ape task), %w(aba are task), %w(aba arf task), %w(baa ape task), %w(baa are task), %w(baa arf task), %w(cab ape task), %w(cab are task), %w(cab arf task), %w(abba pet ark), %w(abba pet ask), %w(abba ret ark), %w(abba ret ask), %w(abba rev ark), %w(abba rev ask), %w(abba set ark), %w(abba set ask), %w(baba pet ark), %w(baba pet ask), %w(baba ret ark), %w(baba ret ask), %w(baba rev ark), %w(baba rev ask), %w(baba set ark), %w(baba set ask), %w(caca pet ark), %w(caca pet ask), %w(caca ret ark), %w(caca ret ask), %w(caca rev ark), %w(caca rev ask), %w(caca set ark), %w(caca set ask)])
    assert_equal(DigitsToWordConverter.new.parse('2282668625'), [%w(acta nounal), %w(act boot oak), %w(act coot oak), %w(bat boot oak), %w(bat coot oak), %w(cat boot oak), %w(cat coot oak), %w(acta mot oak), %w(acta not oak), %w(acta oot oak)])
  end
end